# Generated by Django 5.0.7 on 2024-07-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
