# Generated by Django 5.0.7 on 2024-07-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
